### ISSUE TITLE
Doesn't work in french

### ISSUE THREAD

**Issue by nicolasbraun** [foundry-vtt-community/tables#20]
Hello,

For some reason the rolltable works fine from the compendium when using Foundry in french but once imported it "erases" all the values after first run. Only the few that have the same value remain.
I believe this is because your table references the result by text (thought there is a resultId in the JSON).

![image](https://github.com/foundry-vtt-community/tables/assets/1089363/1bdc76cd-88d8-4990-8f06-bd0af2e2bb68)

May it be useful here is a cleaned json that worked for import, using the Id's in text, note the name.

[common_loot_language_agnostic.json.zip](https://github.com/foundry-vtt-community/tables/files/12706975/common_loot_language_agnostic.json.zip)

Nicolas

**Comment by nicolasbraun** [comment]
PS : Note it also fixes the broken images

**Comment by AnthonyVadala** [comment]
Unable to reproduce bug on latest version of Foundry v12.331 using the French language.

Also the provided table roll table only displays the item IDs and when rolled posts the ID rather than the item.
<img width="722" alt="Screenshot 2024-10-10 at 10 52 27" src="https://github.com/user-attachments/assets/31d9c9b2-f6e0-45f9-83ba-098c96d1c602">
<img width="304" alt="Screenshot 2024-10-10 at 10 52 13" src="https://github.com/user-attachments/assets/06dc7473-1f24-4623-9817-8b0db4dd7eb7">
